# Set the base image to use
FROM gcc:latest
# Copy the C program into the container
COPY lab3.c .
# Compile the C program
RUN gcc -o lab3 lab3.c
# Set the command to run when the container starts
CMD ["./lab3"]